# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
xcodeproj 'wootadmob.xcodeproj'

target 'wootadmob' do
  # pod 'Google-Mobile-Ads-SDK', '~> 7.16.0'
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
end
